authentication/urls.py
from django.contrib import admin
from django.contrib.auth import views as dviews
from django.urls import path,include
from .import views
from django.views.generic import RedirectView

app_name = "auth"
urlpatterns = [
    path('register/', views.register, name="register"),
    path('login', dviews.LoginView.as_view(template_name="login.html"), name="login"),
    path('logout', dviews.LogoutView.as_view(template_name="logout.html"), name="logout"),
    ]

cookbook/urls.py
from django.urls import path, re_path
from . import views


app_name = "cookbook"

urlpatterns = [
     path('search/', views.search, name = 'search'),
     path('sync/',views.sync, name = 'sync'),
     path("recipe_view/<int:pk>", views.recipe_view, name = 'recipe_view'),
     path("save_recipe/", views.save_recipe, name = 'save_recipe'),
     path("remove_recipe/", views.remove_recipe, name = 'remove_recipe'),
     path("saved-recipes/", views.saved_recipes, name = 'saved_recipes'),
]

project/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/',include('authentication.urls')),
    path('cook/',include('cookbook.urls')),
    path('',  views.index, name="index")
]

templates/admin_dashboard.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Admin Dashboard</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/bootstrap.css'%}">
</head>
<body>
    <nav class="bg-black">
        <!-- Navbar content -->
                    <a class="nav-link active" href="#">Home <span class="sr-only"></span></a>
                    <a class="nav-link" href="#">About Us</a>
                    <a class="nav-link" href="#">Register</a>
                    <a class="nav-link" href="#">Login</a>
                </div>
              </div>
            </div>
      </nav> 
    You are Logged In succesfully !! <a href="{% url 'perform_logout' %}">Logout</a>
</body>
</html>

templates/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="description" content="" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    {%load static%}
    <link rel="stylesheet" href="{%static 'css/base.css' %}" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" />
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
    <script src= "https://code.jquery.com/jquery-3.6.0.min.js"> </script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js"></script>
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free@5.15.4/css/fontawesome.min.css" />
    {%block head%}
    {%endblock head%}
  </head>
  <body >
      <nav class="navbar navbar-expand-lg navbar-light">
        <div class="container-fluid">
        <a class="navbar-brand" href="{%url 'index' %}"><img src="{% static 'images/logo2.png' %}" /></a>
          <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav ms-auto">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'index' %}">Home</a>
              </li>
              {% if user.is_authenticated %}
              {%if user.is_staff %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'cookbook:sync' %}">Sync</a>
              </li>
              {%endif%}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'auth:logout' %}">Logout</a>
              </li>
            <form id="f1" class="d-flex" method="post" action="{% url 'cookbook:search' %}">
            {% csrf_token %}
              <input class="form-control me-2" type="search" name="searchbar" placeholder="Search" aria-label="Search" />
              <button class="btn btn-outline-success" type="submit" >Search</button>
            </form>
              <a
                type="button"
                class="btn btn-danger mx-2"
                id="popcart"
                href="{% url 'cookbook:saved_recipes' %}"
                data-container="body"
                data-toggle="popover"
                data-placement="bottom"
                data-html="true">
                      Saved(<span id="saved-recipes">{{user.recipes.count }}</span>)
              </a>
              {% else %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'auth:register' %}">SignUp</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'auth:login'%}">Login</a>
                {%endif%}

              </li>
            </ul>
          </div>
        </div>
      </nav>
    <div class="container  ">
    {% if messages %}
    {% for message in messages %}
    <div class="alert alert-{{message.tags}}"> {{message}} </div>
    {% endfor %}
    {% endif %}
    </div>
    {% block content %}
    {% endblock content %}

</div>

  </body>
</html>
    <script>
{%block scripts%}
{%endblock scripts%}
    </script>

templates/index.html
{%extends 'base.html' %}
{%load static%}
{%block head%}
<link rel="stylesheet" href="{%static 'css/main.css' %}" />
<title>Home</title>
{%endblock%}
{%block content%}
<section class="home">
    <section id="search-bar">
      <div class="container"></div>
      <div class="row"></div>
      <div class="col-lg-15 mx-auto"></div>
      <form action="{% url 'cookbook:search' %}" method="post">
        {% csrf_token %}
        <div class="input-group input-group-lg">
          <input type="search" placeholder="Chase Here..." class="form-control" name="searchbar" />
          <div class="input-group-append"></div>
          <button class="btn btn-warning" value="search" type="submit">Search</button>
        </div>
      </form>
    </section>
</section>
{%endblock content%}

templates/login.html
{%extends 'base.html'%} 
{% load crispy_forms_tags %} 
{%load static %} 
{%block head%}
<link rel="stylesheet" href="{% static 'css/login.css' %}" />
<title>login</title>
{%endblock head%} 
{%block content%}
<section class="Form my-4 mx-5">
  <div class="container">
    <div class="row no-gutters">
      <div class="col-lg-5">
        <img src="{%static 'images/picture1.jpg' %}" class="img-fluid" alt="" />
      </div>
      <div class="col-lg-7 px-5 pt-5">
        <form id="f1" name="f1" method="post">
            {% csrf_token %} 
           {% if form.errors %}
       {% for field in form %}
           {% for error in field.errors %} 
              <div class="alert alert-danger">
                   <strong>{{ error|escape }}</strong>
              </div>
           {% endfor %}
       {% endfor %}
    {% endif %}
          {{form|crispy}}
          <div class="form-row">
            <div class="col-lg-7">
              <button type="submit" form="f1" class="btn1 mt-3 mb-5">Login</button>
            </div>
          </div>
        </form>
        <br />
        <a href="#">Forgot Password?</a><br />
        <p><strong>New User?</strong><a href="{% url 'auth:register' %}">SignUp</a></p>
      </div>
    </div>
  </div>
</section>
{%endblock content%}

templates/logout.html
{% extends 'base.html' %} 
{% block head %}
  <title>Logout</title>
{% endblock %} 
{% block content %}
<h2>You have been logged out</h2>
<div class="border-top pt-3">
  <small class="text-muted"> <a href="{% url 'auth:login' %}">Login again</a></small>
</div>
{% endblock %}

templates/recipe_view.html
{%extends 'base.html' %}
    {%load static%}
    {%block head%}
    <title>Recipe view</title>
    {%endblock head%}

    {%block content%}
    <div class="container my-4">
      <h1>{{name}}</h1>
      <br /><br />
      <div class="row">
        <div class="col-md-6">
          <div class="row">
            <img src="{{img}}" width="233px" height="385px" />
            <p><br /><br /><b> Description:" </b> {{desc}}"</p>
          </div>
          <br /><br />
          <div class="row">
        {% csrf_token %}
            <span id="divpr" class="divpr">
                    {% if user.is_authenticated %}
                    {% if saved %}
                  <button  id="save-button" onclick="save_recipe('{{id}}')" class="btn btn-success save mx-2">Save Recipe</button>
                  {% else %}
                  <button  id="remove-button" onclick="remove_recipe('{{id}}')" class="btn btn-success save mx-2">Remove Recipe</button>
                  {% endif %}
                  {% endif %}
            </span>
          </div>
        </div>
        <div>
          <br /><br />
          {%if ing %}
          <ol>
            <h4>Ingredients</h4>
            {% for i in ing %}
            <li>{{i}}</li>
            {% endfor %}
          </ol>
          {% endif %}
        </div>
        <div>
          <br /><br />
          {%if pre %}
          <ol>
            <h4>Procedure</h4>
            {%for i in pre %}
            <li>{{i}}</li>
            {%endfor%}
          </ol>
          {% endif %}
        </div>
      </div>
    </div>
    {%endblock content%}
{%block scripts%}
function save_recipe(recipe_id) {
        $.ajax({
                type:'POST',
                url:'{% url "cookbook:save_recipe" %}',
            data:
            {
                id:recipe_id,
                csrfmiddlewaretoken:$('input[name=csrfmiddlewaretoken]').val()
            },
            success:function(op, d){
            document.getElementById("save-button").innerHTML = "Saved"
            document.getElementById("saved-recipes").innerHTML = op
                    }
        })
}

function remove_recipe(recipe_id) {
        $.ajax({
                type:'POST',
                url:'{% url "cookbook:remove_recipe" %}',
            data:
            {
                id:recipe_id,
                csrfmiddlewaretoken:$('input[name=csrfmiddlewaretoken]').val()
            },
            success:function(op, d){
            document.getElementById("remove-button").innerHTML = "Removed"
            document.getElementById("saved-recipes").innerHTML = op
                    }
        })
}
{%endblock scripts%}

templates/register.html
{%extends 'base.html'%} 
{%load static %}
{%block head%} 
<link rel="stylesheet" href="{%static 'css/register.css' %}" />
<title> Register </title>
{%endblock%} 
{%block content%} 
{% load crispy_forms_tags %}
<section class="Form my-4 mx-5">
  <div class="container">
    <div class="row no-gutters">
      <div class="col-lg-5">
        <img src="{% static 'images/picture1.jpg' %}" class="img-fluid" alt="" />
      </div>
      <div class="col-lg-7 px-5 pt-5">
        <h3><strong>Create your account</strong></h3>
        <form method="post">
                 {% if form.errors %}
       {% for field in form %}
           {% for error in field.errors %} 
              <div class="alert alert-danger">
                   <strong>{{ error|escape }}</strong>
              </div>
           {% endfor %}
       {% endfor %}
    {% endif %}
          {% csrf_token %} {{form|crispy}}
          <button type="submit" class="btn1 mt-3 mb-5">SignUp</button>
        </form>
        <br />
        <p><strong>Already a User?</strong><a href="{% url 'auth:login' %}">Login</a></p>
      </div>
    </div>
  </div>
</section>
{%endblock content%}

templates/saved_recipes.html
{%extends 'base.html'%} {%load static%} {%block head%}
<link rel="stylesheet" href="{% static 'css/search.css' %}" />
<title>Saved Recipes</title>
{%endblock head%} 
{%block content%} 
{% if recipes %} 
{% for r in recipes|slice:"0:" %}
{% csrf_token %}
<div class="container">
  <div class="row">
    <div class="col-lg-4 mb-2">
      <div class="card">
        <img src="{{r.img_url}}" class="card-img-top" alt="..." />
        <div class="card-body">
          <h5 class="card-title">{{ r.recipe_name }}</h5>
          <p class="card-text">{{r.domain}}</p>
          <a href="/cook/recipe_view/{{r.recipe.id}}">
            <button id="{{r.recipe_name}}" class="btn btn-success">View Recipe</button></a
          >
          <span id="divpr{{r.url}}" class="divpr">
                  <button  onclick="remove_recipe('{{r.id}}')" class="btn btn-success save mx-2">Remove Recipe</button>
          </span>
        </div>
        {% if forloop.counter|divisibleby:3 and forloop.counter > 0 and not forloop.last %}
      </div>
      <div class="container">{% endif%}</div>
    </div>
  </div>
</div>
{% endfor %} {% else %}
<p>No such recipe available.</p>
{% endif %} 
{%endblock content%} 
{%block scripts%}
function remove_recipe(recipe_id) {
        $.ajax({
                type:'POST',
                url:'{% url "cookbook:remove_recipe" %}',
            data:
            {
                id:recipe_id,
                csrfmiddlewaretoken:$('input[name=csrfmiddlewaretoken]').val()
            },
            success:function(op, d){
            document.getElementById("saved-recipes").innerHTML = op
                    }
        })
}
{%endblock scripts%}

templates/search_result.html
{%extends 'base.html'%} {%load static%} {%block head%}
<link rel="stylesheet" href="{% static 'css/search.css' %}" />
<title>Home</title>
{%endblock head%} 
{%block content%} 
{% if result %} 
{% for r in result|slice:"0:" %}
{% csrf_token %}
<div class="container">
  <div class="row">
    <div class="col-lg-4 mb-2">
      <div class="card">
        <img src="{{r.img_url}}" class="card-img-top" alt="..." />
        <div class="card-body">
          <h5 class="card-title">{{ r.recipe_name }}</h5>
          <p class="card-text">{{r.domain}}</p>
          <a href="/cook/recipe_view/{{r.recipe.id}}">
            <button id="{{r.recipe_name}}" class="btn btn-success">View Recipe</button></a
          >
          {% if user.is_authenticated %}
          <span id="divpr{{r.url}}" class="divpr">
                  <button  onclick="save_recipe('{{r.id}}')" class="btn btn-success save mx-2">Save Recipe</button>
          </span>
          {% endif%}
        </div>
        {% if forloop.counter|divisibleby:3 and forloop.counter > 0 and not forloop.last %}
      </div>
      <div class="container">{% endif%}</div>
    </div>
  </div>
</div>
{% endfor %} {% else %}
<p>No such recipe available.</p>
{% endif %} 
{%endblock content%} 
{%block scripts%}
function save_recipe(recipe_id) {
        $.ajax({
                type:'POST',
                url:'{% url "cookbook:save_recipe" %}',
            data:
            {
                id:recipe_id,
                csrfmiddlewaretoken:$('input[name=csrfmiddlewaretoken]').val()
            },
            success:function(op, d){
            document.getElementById("saved-recipes").innerHTML = op
                    }
        })
}
{%endblock scripts%}